export const GENRES = {
  ALL: 'ALL',
  DOCUMENTARY: 'DOCUMENTARY',
  COMEDY: 'COMEDY',
  HORROR: 'HORROR',
  CRIME: 'CRIME'
};

export const GENRES_LIST = ['ALL','DOCUMENTARY', 'COMEDY', 'HORROR','CRIME'];
